/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.miguelyac.vista;

import java.awt.Graphics;
import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.miguelyac.controlador.adminDAO;
import org.miguelyac.modelo.LoginAdmin;

/**
 *
 * @author santiago
 */
class PanelDeImagen extends JPanel{
    private Image imagen;
    public PanelDeImagen(Image imagen){
        this.imagen = imagen;
    }
    @Override
    protected void paintComponent(Graphics grafica){
        super.paintComponent(grafica);
        grafica.drawImage(imagen,0,0,500,570,this);
    }
}
public class VentanaAdmin extends javax.swing.JFrame {
    LoginAdmin lg = new LoginAdmin();
    adminDAO login = new adminDAO();
    private Image imagenDeFondo;

        public void Validar(){
        String correo_admin = txtCorreo.getText();
        String pass_admin = String.valueOf(txtPass.getPassword());
        if(!"".equals(correo_admin) || !"".equals(pass_admin)){
            lg = login.log(correo_admin, pass_admin);
            if(lg.getCorreo_admin()!=null && lg.getPass_admin()!=null){
                this.setVisible(false);
                Principal PA = new Principal();
                PA.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "Correo y/o contraseña incorrrecto");
            }
        }
    }
    public VentanaAdmin() {
        String nombreDeImagen = "/org/miguelyac/recursos/FondoConstruccion.png";
        cargarImagenDeFondo(this.getClass().getResource(nombreDeImagen));
        initComponents();
        this.setLocationRelativeTo(null);
    }
    private void cargarImagenDeFondo(URL nombreDeImagen){
        try{
            imagenDeFondo = ImageIO.read(nombreDeImagen);
        }catch(IOException error){
            error.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDeAdmin = new PanelDeImagen(imagenDeFondo);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnIngresarAdmin = new javax.swing.JButton();
        txtPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelDeAdmin.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/miguelyac/recursos/Logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ᴄᴏʀʀᴇᴏ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ᴄᴏɴᴛʀᴀꜱᴇÑᴀ");

        btnIngresarAdmin.setFont(new java.awt.Font("Segoe UI Emoji", 3, 18)); // NOI18N
        btnIngresarAdmin.setText("Ingresar");
        btnIngresarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDeAdminLayout = new javax.swing.GroupLayout(PanelDeAdmin);
        PanelDeAdmin.setLayout(PanelDeAdminLayout);
        PanelDeAdminLayout.setHorizontalGroup(
            PanelDeAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDeAdminLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelDeAdminLayout.createSequentialGroup()
                .addGroup(PanelDeAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDeAdminLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(PanelDeAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPass)))
                    .addGroup(PanelDeAdminLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(btnIngresarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        PanelDeAdminLayout.setVerticalGroup(
            PanelDeAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDeAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(btnIngresarAdmin)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        getContentPane().add(PanelDeAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarAdminActionPerformed
       Validar();
    }//GEN-LAST:event_btnIngresarAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDeAdmin;
    private javax.swing.JButton btnIngresarAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
